{
  "openapi": "3.0.3",
  "info": {
    "title": "Desafio_LinkApi",
    "description": "API para visualizar os dados dos usuários listados na MockApi fornecida",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:3000/",
      "description": "API para teste"
    }
  ],
  "paths": {
    "/users": {
      "get": {
        "description": "Rota que retorna os usuários junto com seu endereço e contato",
        "summary": "Listar usuários",
        "tags": ["Users"],
        "parameters": [
          {
            "name": "page",
            "in": "query",
            "description": "Qual página será exibida",
            "required": false,
            "value": "1"
          },
          {
            "name": "limit",
            "in": "query",
            "description": "Quantidade de elementos a serem retornados por página",
            "required": false,
            "value": "10"
          },
          {
            "name": "sortBy",
            "in": "query",
            "description": "Campo que será considerado na ordenação de dados",
            "required": false
          },
          {
            "name": "order",
            "in": "query",
            "description": "Ordem de classificação (asc ou desc)",
            "required": false
          }
        ],
        "responses": {
          "400": {
            "description": "Erro ao buscar os usuários",
            "content": {
              "applcation/json": {
                "schema": {
                  "type": "object"
                },
                "examples": {
                  "error": {
                    "value": {
                      "error": "Erro ao buscar os usuários"
                    }
                  }
                }
              }
            }
          },
          "200": {
            "description": "OK",
            "content": {
              "applcation/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/User"
                },
                "examples": {
                  "user": {
                    "value": {
                      "id": "1",
                      "createdAt": "2022-02-09T20:58:14.264Z",
                      "fullName": "Italo Felipe Ignacio",
                      "email": "italo.felipe.ignacio@hotmail.com",
                      "addresses": {
                        "addressId": "1",
                        "address": "Alameda dos antúrios 201 ",
                        "country": "Brasil",
                        "countryCode": "BR",
                        "city": "Santana de parnaíba",
                        "state": "São Paulo",
                        "zipcode": "06539-110"
                      },
                      "contacts": {
                        "contactId": "1",
                        "name": "Italo",
                        "phoneNumber": "(11) 94190-1415",
                        "email": "italo.felipe.ignacio@hotmail.com"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/{userId}/address": {
      "get": {
        "description": "Rota que retorna o endereço do usuários pelo ID",
        "summary": "Listar endereços do usuário pelo ID",
        "tags": ["Users"],
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "description": "ID do usuários q será exibido",
            "required": true
          }
        ],
        "responses": {
          "400": {
            "description": "Erro ao buscar o endereço",
            "content": {
              "applcation/json": {
                "schema": {
                  "type": "object"
                },
                "examples": {
                  "error": {
                    "value": {
                      "error": "Erro ao buscar o endereço"
                    }
                  }
                }
              }
            }
          },
          "200": {
            "description": "OK",
            "content": {
              "applcation/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Address"
                },
                "examples": {
                  "address": {
                    "value": {
                      "addressId": "1",
                      "address": "Alameda dos antúrios 201 ",
                      "country": "Brasil",
                      "countryCode": "BR",
                      "city": "Santana de parnaíba",
                      "state": "São Paulo",
                      "zipcode": "06539-110"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/{userId}/contact": {
      "get": {
        "description": "Rota que retorna o contato do usuários pelo ID",
        "summary": "Listar contatos do usuário pelo ID",
        "tags": ["Users"],
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "description": "ID do usuários q será exibido",
            "required": true
          }
        ],
        "responses": {
          "400": {
            "description": "Erro ao buscar o contato",
            "content": {
              "applcation/json": {
                "schema": {
                  "type": "object"
                },
                "examples": {
                  "error": {
                    "value": {
                      "error": "Erro ao buscar o contato"
                    }
                  }
                }
              }
            }
          },
          "200": {
            "description": "OK",
            "content": {
              "applcation/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Contact"
                },
                "examples": {
                  "contact": {
                    "value": {
                      "contactId": "1",
                      "name": "Italo",
                      "phoneNumber": "(11) 94190-1415",
                      "email": "italo.felipe.ignacio@hotmail.com"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "User": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "createdAt": {
            "type": "string"
          },
          "fullName": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "addresses": {
            "type": "object",
            "$ref": "#/components/schemas/Address"
          },
          "contacts": {
            "type": "object",
            "$ref": "#/components/schemas/Contact"
          }
        }
      },
      "Address": {
        "type": "object",
        "properties": {
          "addressId": {
            "type": "string"
          },
          "address": {
            "type": "string"
          },
          "country": {
            "type": "string"
          },
          "countryCode": {
            "type": "string"
          },
          "city": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "zipcode": {
            "type": "string"
          }
        }
      },
      "Contact": {
        "type": "object",
        "properties": {
          "contactId": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "phoneNumber": {
            "type": "string"
          },
          "email": {
            "type": "string"
          }
        }
      }
    }
  }
}
